// Hardcoded symbol catalogue shown in the Asset Alert form's dropdown,
// keyed by asset_type. WatchTower's backend accepts any 1-20 char
// uppercase/hyphen symbol (see internal/user.assetSymbolPattern), so this
// list is a curated UX convenience, not a validation whitelist enforced
// server-side.
export const ASSET_OPTIONS = {
  crypto: [
    { label: 'BTC - Bitcoin', value: 'BTC' },
    { label: 'ETH - Ethereum', value: 'ETH' },
    { label: 'BNB - BNB', value: 'BNB' },
    { label: 'SOL - Solana', value: 'SOL' },
    { label: 'XRP - XRP', value: 'XRP' },
    { label: 'DOGE - Dogecoin', value: 'DOGE' },
    { label: 'ADA - Cardano', value: 'ADA' },
    { label: 'TRX - TRON', value: 'TRX' },
    { label: 'AVAX - Avalanche', value: 'AVAX' },
    { label: 'SHIB - Shiba Inu', value: 'SHIB' },
    { label: 'TON - Toncoin', value: 'TON' },
    { label: 'LINK - Chainlink', value: 'LINK' },
    { label: 'DOT - Polkadot', value: 'DOT' },
    { label: 'MATIC - Polygon', value: 'MATIC' },
    { label: 'DAI - Dai', value: 'DAI' },
    { label: 'UNI - Uniswap', value: 'UNI' },
    { label: 'ATOM - Cosmos', value: 'ATOM' },
    { label: 'LTC - Litecoin', value: 'LTC' },
    { label: 'BCH - Bitcoin Cash', value: 'BCH' },
    { label: 'NEAR - NEAR Protocol', value: 'NEAR' },
  ],
  stock: [
    { label: 'AAPL - Apple Inc.', value: 'AAPL' },
    { label: 'MSFT - Microsoft', value: 'MSFT' },
    { label: 'NVDA - NVIDIA', value: 'NVDA' },
    { label: 'GOOGL - Alphabet (Google)', value: 'GOOGL' },
    { label: 'AMZN - Amazon', value: 'AMZN' },
    { label: 'META - Meta Platforms', value: 'META' },
    { label: 'TSLA - Tesla', value: 'TSLA' },
    { label: 'NFLX - Netflix', value: 'NFLX' },
    { label: 'TSM - Taiwan Semiconductor', value: 'TSM' },
    { label: 'AVGO - Broadcom', value: 'AVGO' },
    { label: 'JPM - JPMorgan Chase', value: 'JPM' },
    { label: 'LLY - Eli Lilly', value: 'LLY' },
    { label: 'V - Visa', value: 'V' },
    { label: 'UNH - UnitedHealth Group', value: 'UNH' },
    { label: 'XOM - ExxonMobil', value: 'XOM' },
    { label: 'MA - Mastercard', value: 'MA' },
    { label: 'JNJ - Johnson & Johnson', value: 'JNJ' },
    { label: 'PG - Procter & Gamble', value: 'PG' },
    { label: 'HD - Home Depot', value: 'HD' },
    { label: 'COST - Costco', value: 'COST' },
  ],
  gold: [
    { label: 'ANTAM - Antam (IDR)', value: 'ANTAM' },
    { label: 'XAU - Gold (USD)', value: 'XAU' },
  ],
}
